version: "3.9"
services:
  blog_web:
    container_name: blog_web
    build:
      context: .
      dockerfile: ./Dockerfile.web
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog_web.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.blog_web.entrypoints=websecure"
      - "traefik.http.routers.blog_web.tls.certresolver=myresolver"
  blog_db:
    container_name: blog_db
    build:
      context: .
      dockerfile: ./Dockerfile.db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: blog
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    networks:
      - traefik

networks:
  traefik:
    external: true
