version: "3.9"
services:
  web:
    container_name: blog_web
    build:
      context: .
      dockerfile: ./Dockerfile.web
    ports:
      - 80:80
    restart: always
    networks:
      - app
  db:
    container_name: blog_db
    build:
      context: .
      dockerfile: ./Dockerfile.db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: blog
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - app
#  debug2:
#    container_name: debug2
#    image: aries1980/network-tools
#    command: tail -f /dev/null
#    restart: always
#    networks:
#      - app
#  debug:
#    container_name: debug
#    image: aries1980/network-tools
#    command: tail -f /dev/null
#    restart: always
#    networks:
#      - app
#
networks:
  app:
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
       - subnet: 2001:3984:3989::/64
