version: "3.9"
services:
  web:
    container_name: blog_web
    build:
      context: .
      dockerfile: ./Dockerfile.web
    ports:
      - "80:80"
    restart: always
  db:
    container_name: blog_db
    build:
      context: .
      dockerfile: ./Dockerfile.db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: blog
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
